#define PACKAGE_NAME "The-Zero-Debugger"
#define PACKAGE_TARNAME "the-zero-debugger"
#define PACKAGE_VERSION "1.16"
#define PACKAGE_STRING "The-Zero-Debugger 1.16"
#define PACKAGE_BUGREPORT "http://www.zerobugs.org"
#define HAVE_LIBPTHREAD 1
#define HAVE_LIBMINIELF 1
#define HAVE_LIBDWARF 1
#define HAVE_DIRENT_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_FCNTL_H 1
#define HAVE_LIBGEN_H 1
#define HAVE_LIBINTL_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MALLOC_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_FILE_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_SYSINFO_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_TERMCAP_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_UNISTD_H 1
#define HAVE_UUID_UUID_H 1
#define HAVE_LIBSSL 1
#define HAVE_LIBSQLITE3 1
#define HAVE_THREAD_DB_H 1
#define HAVE_ASM_PTRACE_H 1
#define HAVE_ASM_PRCTL_H 1
#define HAVE_ASM_LDT_H 1
#define HAVE_ASM_UNISTD_H 1
#define HAVE_ATOMIC_OPS_H 1
#define HAVE_STDBOOL_H 1
#define restrict __restrict
#define TIME_WITH_SYS_TIME 1
#define HAVE_STRUCT_USER_FPREGS_STRUCT 1
#define HAVE_STRUCT_USER_DESC 1
#define HAVE_THREAD_T 1
#define HAVE___UINT32_T 1
#define HAVE___UINT64_T 1
#define HAVE_FORK 1
#define HAVE_VFORK 1
#define HAVE_WORKING_VFORK 1
#define GETPGRP_VOID 1
#define HAVE_STDLIB_H 1
#define HAVE_UNISTD_H 1
#define HAVE_GETPAGESIZE 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_SOCKET_H 1
#define SELECT_TYPE_ARG1 int
#define SELECT_TYPE_ARG234 (fd_set *)
#define SELECT_TYPE_ARG5 (struct timeval *)
#define RETSIGTYPE void
#define HAVE_STAT_EMPTY_STRING_BUG 1
#define HAVE_STRFTIME 1
#define HAVE_ATEXIT 1
#define HAVE_DUP2 1
#define HAVE_FTRUNCATE 1
#define HAVE_GETCWD 1
#define HAVE_GETPAGESIZE 1
#define HAVE_MEMSET 1
#define HAVE_MKDIR 1
#define HAVE_MUNMAP 1
#define HAVE_POW 1
#define HAVE_REALPATH 1
#define HAVE_RMDIR 1
#define HAVE_SELECT 1
#define HAVE_SETENV 1
#define HAVE_STRCHR 1
#define HAVE_STRDUP 1
#define HAVE_STRERROR 1
#define HAVE_STRNCASECMP 1
#define HAVE_STRRCHR 1
#define HAVE_STRSTR 1
#define HAVE_STRTOL 1
#define HAVE_STRTOUL 1
#define HAVE_STRTOULL 1
#define HAVE_UNAME 1
#define HAVE_SQLITE3_PREPARE_V2 1
