import zero

def my_command(thread, args):
	#print '----- user defined command -----'
	pc = thread.program_count()
	print "current function range: [%x-%x)" % thread.fun_range(pc)
	print "%s:%d [%x-%x)" % thread.process().line_info(pc)
	return thread.debugger().command("next", thread)

	#thread.step(zero.Step.OverStatement)
	#return True


xpm = """
20 20 2 1
  c darkgreen
. c none
....................
....................
.......... .........
..........  ........
..........   .......
..........    ......
..........     .....
...             ....
...              ...
...               ..
...               ..
...              ...
...             ....
..........     .....
..........    ......
..........   .......
..........  ........
.......... .........
....................
....................
"""


def on_init(debugger):
	print '----- on_init -----'
	attr = { 
		"help":"example", 
		"type":"tool", 
		"tool":"_Custom",
		"pixmap":xpm, 
		#"stock":"gtk-media-next",
		"tooltip":"custom command example",
	}

	debugger.def_command("my_next", my_command, attr)

