# vim: noexpandtab: tabstop=4: shiftwidth=4
# $Id$
#
ifeq ($(TOP),)
 TOP=../..
endif

include $(TOP)/zdk/make/Common.mak

LIBS=-lzdk
LDLIBS+=-lpthread

LDFLAGS+=-Wl,--no-undefined

################################################################
SRCS=\
	${PLUGIN_NAME}.cpp \
	$(NULL)

PLUGIN=$(PLUGIN_PATH)${PLUGIN_NAME}.so
TARGET=$(PLUGIN)

################################################################

all: $(PLUGIN)

$(PLUGIN): $(LIB_FILES) $(OBJS)
	mkdir -p $(PLUGIN_PATH)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -shared $(OBJS) -o $@ $(LDLIBS)


include $(TOP)/zdk/make/Epilogue.mak
